export const OfferApi = [
  {
    id: 1,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Candies",
  },
  {
    id: 2,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/about",
    title: "Chocolate Bars",
  },
  {
    id: 3,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/product",
    title: "Cakes",
  },
  {
    id: 4,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Brownies",
  },
  {
    id: 5,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Cupcakes",
  },
  {
    id: 6,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Desserts",
  },
  {
    id: 7,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Bun & Bread",
  },
  {
    id: 8,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Patties",
  },

  {
    id: 9,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Cookies",
  },
  {
    id: 10,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Crackers",
  },
  {
    id: 11,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Biscuits",
  },
  {
    id: 12,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/about",
    title: "Rolls",
  },
  {
    id: 13,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/product",
    title: "Pies",
  },
  {
    id: 14,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Pastries",
  },
  {
    id: 15,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Doughnuts",
  },
  {
    id: 16,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Muffins",
  },
  {
    id: 17,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Burger",
  },
  {
    id: 18,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Pizza",
  },

  {
    id: 19,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Sweets",
  },
  {
    id: 20,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Tarts",
  },
];

export const FeaturesApi = [
  {
    id: 1,
    heading: "A Delectable Journey Of Mystery And Desire",
    image: "./images/features/features_1.jpg",
    imageAlt: "Features Item",
    to: "/singleproduct/:id",
  },
  {
    id: 2,
    heading: "A Delectable Journey Of Mystery And Desire",
    image: "./images/features/features_2.jpg",
    imageAlt: "Features Item",
    to: "/cart",
  },
  {
    id: 3,
    heading: "A Delectable Journey Of Mystery And Desire",
    image: "./images/features/features_3.jpg",
    imageAlt: "Features Item",
    to: "/about",
  },
  {
    id: 4,
    heading: "A Delectable Journey Of Mystery And Desire",
    image: "./images/features/features_4.jpg",
    imageAlt: "Features Item",
    to: "/",
  },
];

export const ProductListFirstApi = [
  {
    id: 1,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Mix Nuts Chocolate Candy",
    qty: "1 Box (100pcs)",
    discount: "5% off",
    prevPrice: "₹300",
    price: 250,
    to: "/singleproduct/:id",
  },
  {
    id: 2,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Almond Chocolate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 3,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Cashew Chocolate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 4,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Mix Nuts Choclate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 5,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Almond Triangle Chocolate",
    qty: "1 Box (100pcs)",
    price: 180,
    to: "/singleproduct/:id",
  },
  {
    id: 6,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Nut Square Chocolate",
    qty: "1 Box (100pcs)",
    price: 200,
    to: "/singleproduct/:id",
  },
];

export const ProductListSecondApi = [
  {
    id: 1,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Mix Nuts Chocolate Candy",
    qty: "1 Box (100pcs)",
    discount: "5% off",
    prevPrice: "₹300",
    price: 250,
    to: "/singleproduct/:id",
  },
  {
    id: 2,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Almond Chocolate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 3,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Cashew Chocolate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 4,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Mix Nuts Choclate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 5,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Almond Triangle Chocolate",
    qty: "1 Box (100pcs)",
    price: 180,
    to: "/singleproduct/:id",
  },
  {
    id: 6,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Nut Square Chocolate",
    qty: "1 Box (100pcs)",
    price: 200,
    to: "/singleproduct/:id",
  },
];

export const ProductListThirdApi = [
  {
    id: 1,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Mix Nuts Chocolate Candy",
    qty: "1 Box (100pcs)",
    discount: "5% off",
    prevPrice: "₹300",
    price: 250,
    to: "/singleproduct/:id",
  },
  {
    id: 2,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Almond Chocolate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 3,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Cashew Chocolate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 4,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Mix Nuts Choclate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 5,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Almond Triangle Chocolate",
    qty: "1 Box (100pcs)",
    price: 180,
    to: "/singleproduct/:id",
  },
  {
    id: 6,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Nut Square Chocolate",
    qty: "1 Box (100pcs)",
    price: 200,
    to: "/singleproduct/:id",
  },
];

export const ProductListForthApi = [
  {
    id: 1,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Mix Nuts Chocolate Candy",
    qty: "1 Box (100pcs)",
    discount: "5% off",
    prevPrice: "₹300",
    price: 250,
    to: "/singleproduct/:id",
  },
  {
    id: 2,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Almond Chocolate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 3,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Cashew Chocolate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 4,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Mix Nuts Choclate Bar",
    qty: "50g",
    price: 25,
    to: "/singleproduct/:id",
  },
  {
    id: 5,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Almond Triangle Chocolate",
    qty: "1 Box (100pcs)",
    price: 180,
    to: "/singleproduct/:id",
  },
  {
    id: 6,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Product Items",
    stock: "Available",
    name: "Best Sale Nut Square Chocolate",
    qty: "1 Box (100pcs)",
    price: 200,
    to: "/singleproduct/:id",
  },
];

export const FooterMenu = [
  {
    id: 1,
    name: "About Us",
    link: "/about",
  },
  {
    id: 2,
    name: "Contact Us",
    link: "/contact",
  },
  {
    id: 3,
    name: "Career",
    link: "/career",
  },
  {
    id: 4,
    name: "Blog",
    link: "/blog",
  },
  {
    id: 5,
    name: "Bake Farm's Wholesale",
    link: "/",
  },
  {
    id: 6,
    name: "Corporate Information",
    link: "/",
  },
  {
    id: 7,
    name: "Payments",
    link: "/",
  },
  {
    id: 8,
    name: "Shipping",
    link: "/",
  },
  {
    id: 9,
    name: "Cancellation & Returns",
    link: "/",
  },
  {
    id: 10,
    name: "FAQ",
    link: "/",
  },
  {
    id: 11,
    name: "Privacy",
    link: "/",
  },
  {
    id: 12,
    name: "Sitemap",
    link: "/",
  },
  {
    id: 13,
    name: "Facebook",
    link: "/about",
  },
  {
    id: 14,
    name: "Twitter",
    link: "/",
  },
  {
    id: 15,
    name: "Instagram",
    link: "/blog",
  },
  {
    id: 16,
    name: "Whatsapp",
    link: "/",
  },
  {
    id: 17,
    name: "Youtube",
    link: "/",
  },
  {
    id: 18,
    name: "Candies",
    link: "/singleproduct/:id",
  },
  {
    id: 19,
    name: "Chocolate Bars",
    link: "/singleproduct/:id",
  },
  {
    id: 20,
    name: "Cakes",
    link: "/singleproduct/:id",
  },
  {
    id: 21,
    name: "Brownies",
    link: "/singleproduct/:id",
  },
  {
    id: 22,
    name: "Cupcakes",
    link: "/singleproduct/:id",
  },
  {
    id: 23,
    name: "Desserts",
    link: "/singleproduct/:id",
  },
  {
    id: 24,
    name: "Bun & Bread",
    link: "/singleproduct/:id",
  },
  {
    id: 25,
    name: "Patties",
    link: "/singleproduct/:id",
  },
  {
    id: 26,
    name: "Cookies",
    link: "/singleproduct/:id",
  },
  {
    id: 27,
    name: "Crackers",
    link: "/singleproduct/:id",
  },
  {
    id: 28,
    name: "Biscuits",
    link: "/singleproduct/:id",
  },
  {
    id: 29,
    name: "Rolls",
    link: "/singleproduct/:id",
  },
  {
    id: 30,
    name: "Pies",
    link: "/singleproduct/:id",
  },
  {
    id: 31,
    name: "Pastries",
    link: "/singleproduct/:id",
  },
  {
    id: 32,
    name: "Doughnuts",
    link: "/singleproduct/:id",
  },
  {
    id: 33,
    name: "Muffins",
    link: "/singleproduct/:id",
  },
  {
    id: 34,
    name: "Berger",
    link: "/singleproduct/:id",
  },
  {
    id: 35,
    name: "Pizza",
    link: "/singleproduct/:id",
  },
  {
    id: 36,
    name: "Sweets",
    link: "/singleproduct/:id",
  },
  {
    id: 37,
    name: "Tarts",
    link: "/singleproduct/:id",
  },
];
