export const OfferApi = [
  {
    id: 1,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Candies",
  },
  {
    id: 2,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/about",
    title: "Chocolates",
  },
  {
    id: 3,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/product",
    title: "Cakes",
  },
  {
    id: 4,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Brownies",
  },
  {
    id: 5,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Cupcakes",
  },
  {
    id: 6,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Desserts",
  },
  {
    id: 7,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Bun & Bread",
  },
  {
    id: 8,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Patties",
  },

  {
    id: 9,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Cookies",
  },
  {
    id: 10,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Crackers",
  },
  {
    id: 11,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Biscuits",
  },
  {
    id: 12,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/about",
    title: "Rolls",
  },
  {
    id: 13,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/product",
    title: "Pies",
  },
  {
    id: 14,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Pastries",
  },
  {
    id: 15,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Doughnuts",
  },
  {
    id: 16,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Muffins",
  },
  {
    id: 17,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Burger",
  },
  {
    id: 18,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Pizza",
  },

  {
    id: 19,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Sweets",
  },
  {
    id: 20,
    image: "./images/categories/candies_chocolates.jpg",
    imageAlt: "Categories Item",
    to: "/",
    title: "Tarts",
  },
];

export const FeaturesApi = [
  {
    id: 1,
    heading: "A Delectable Journey Of Mystery And Desire",
    image: "./images/features/features_1.jpg",
    imageAlt: "Features Item",
    to: "/products",
  },
  {
    id: 2,
    heading: "A Delectable Journey Of Mystery And Desire",
    image: "./images/features/features_2.jpg",
    imageAlt: "Features Item",
    to: "/cart",
  },
  {
    id: 3,
    heading: "A Delectable Journey Of Mystery And Desire",
    image: "./images/features/features_3.jpg",
    imageAlt: "Features Item",
    to: "/about",
  },
  {
    id: 4,
    heading: "A Delectable Journey Of Mystery And Desire",
    image: "./images/features/features_4.jpg",
    imageAlt: "Features Item",
    to: "/",
  },
];
